//Copyright (c) 2017 Finjin
//
//This file is part of Finjin Engine (finjin-engine).
//
//Finjin Engine is distributed in the hope that it will be useful,
//but WITHOUT ANY WARRANTY; without even the implied warranty of
//MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
//
//This Source Code Form is subject to the terms of the Mozilla Public
//License, v. 2.0. If a copy of the MPL was not distributed with this
//file, You can obtain one at http://mozilla.org/MPL/2.0/.


#if FINJIN_TARGET_PLATFORM == FINJIN_TARGET_PLATFORM_IOS
    //iOS_GPUFamily1_v1
    {
        MTLFeatureSet_iOS_GPUFamily1_v1, Version(1, 1),
        //Availability
        {
            true,
            false,
            true,
            true,
            true,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
        },
        //Limits
        {
            31,
            31,
            31,
            16,
            31,
            4000,
            512,
            16352,
            16,
            (size_t)-1,
            60,
            60,
            0,
            0,
            256000000,
            4,
            4096,
            4096,
            4096,
            2048,
            2048,
            64,
            64,
            4,
            511,
            16,
            65528,
        },
        //Capabilities
        {
            MetalFeatureSetCapability::FILTER,
            MetalFeatureSetCapability::ALL,
            MetalFeatureSetCapability::FILTER | MetalFeatureSetCapability::COLOR | MetalFeatureSetCapability::MSAA | MetalFeatureSetCapability::RESOLVE | MetalFeatureSetCapability::BLEND,
            MetalFeatureSetCapability::FILTER | MetalFeatureSetCapability::WRITE | MetalFeatureSetCapability::COLOR | MetalFeatureSetCapability::MSAA | MetalFeatureSetCapability::BLEND,
            MetalFeatureSetCapability::WRITE | MetalFeatureSetCapability::COLOR | MetalFeatureSetCapability::MSAA,
            MetalFeatureSetCapability::FILTER | MetalFeatureSetCapability::WRITE | MetalFeatureSetCapability::COLOR | MetalFeatureSetCapability::MSAA | MetalFeatureSetCapability::BLEND,
            MetalFeatureSetCapability::WRITE | MetalFeatureSetCapability::COLOR | MetalFeatureSetCapability::MSAA,
            MetalFeatureSetCapability::ALL,
            MetalFeatureSetCapability::ALL,
            MetalFeatureSetCapability::FILTER | MetalFeatureSetCapability::COLOR | MetalFeatureSetCapability::MSAA | MetalFeatureSetCapability::RESOLVE | MetalFeatureSetCapability::BLEND,
            MetalFeatureSetCapability::FILTER | MetalFeatureSetCapability::WRITE | MetalFeatureSetCapability::COLOR | MetalFeatureSetCapability::MSAA | MetalFeatureSetCapability::BLEND,
            MetalFeatureSetCapability::WRITE | MetalFeatureSetCapability::COLOR | MetalFeatureSetCapability::MSAA,
            MetalFeatureSetCapability::FILTER | MetalFeatureSetCapability::COLOR | MetalFeatureSetCapability::MSAA | MetalFeatureSetCapability::RESOLVE | MetalFeatureSetCapability::BLEND,
            MetalFeatureSetCapability::COLOR,
            MetalFeatureSetCapability::COLOR | MetalFeatureSetCapability::MSAA,
            MetalFeatureSetCapability::FILTER | MetalFeatureSetCapability::WRITE | MetalFeatureSetCapability::COLOR | MetalFeatureSetCapability::MSAA | MetalFeatureSetCapability::BLEND,
            MetalFeatureSetCapability::WRITE | MetalFeatureSetCapability::COLOR | MetalFeatureSetCapability::MSAA,
            MetalFeatureSetCapability::ALL,
            MetalFeatureSetCapability::ALL,
            MetalFeatureSetCapability::FILTER | MetalFeatureSetCapability::COLOR | MetalFeatureSetCapability::MSAA | MetalFeatureSetCapability::RESOLVE | MetalFeatureSetCapability::BLEND,
            MetalFeatureSetCapability::FILTER | MetalFeatureSetCapability::WRITE | MetalFeatureSetCapability::COLOR | MetalFeatureSetCapability::MSAA | MetalFeatureSetCapability::BLEND,
            MetalFeatureSetCapability::WRITE | MetalFeatureSetCapability::COLOR | MetalFeatureSetCapability::MSAA,
            MetalFeatureSetCapability::ALL,
            MetalFeatureSetCapability::FILTER | MetalFeatureSetCapability::COLOR | MetalFeatureSetCapability::MSAA | MetalFeatureSetCapability::RESOLVE | MetalFeatureSetCapability::BLEND,
            MetalFeatureSetCapability::FILTER | MetalFeatureSetCapability::COLOR | MetalFeatureSetCapability::MSAA | MetalFeatureSetCapability::RESOLVE | MetalFeatureSetCapability::BLEND,
            MetalFeatureSetCapability::COLOR | MetalFeatureSetCapability::MSAA,
            MetalFeatureSetCapability::FILTER | MetalFeatureSetCapability::COLOR | MetalFeatureSetCapability::MSAA | MetalFeatureSetCapability::RESOLVE | MetalFeatureSetCapability::BLEND,
            MetalFeatureSetCapability::FILTER | MetalFeatureSetCapability::COLOR | MetalFeatureSetCapability::MSAA | MetalFeatureSetCapability::RESOLVE | MetalFeatureSetCapability::BLEND,
            MetalFeatureSetCapability::COLOR,
            MetalFeatureSetCapability::COLOR,
            MetalFeatureSetCapability::FILTER | MetalFeatureSetCapability::WRITE | MetalFeatureSetCapability::COLOR | MetalFeatureSetCapability::MSAA | MetalFeatureSetCapability::BLEND,
            MetalFeatureSetCapability::WRITE | MetalFeatureSetCapability::COLOR | MetalFeatureSetCapability::MSAA,
            MetalFeatureSetCapability::ALL,
            MetalFeatureSetCapability::COLOR,
            MetalFeatureSetCapability::COLOR,
            MetalFeatureSetCapability::FILTER,
            MetalFeatureSetCapability::FILTER,
            MetalFeatureSetCapability::NONE,
            MetalFeatureSetCapability::NONE,
            MetalFeatureSetCapability::FILTER,
            MetalFeatureSetCapability::NONE,
            MetalFeatureSetCapability::MSAA,
            MetalFeatureSetCapability::MSAA,
            MetalFeatureSetCapability::NONE,
            MetalFeatureSetCapability::MSAA,
            MetalFeatureSetCapability::NONE,
            MetalFeatureSetCapability::MSAA,
            MetalFeatureSetCapability::NONE,
        },
    },
#endif
#if FINJIN_TARGET_PLATFORM == FINJIN_TARGET_PLATFORM_IOS
    //iOS_GPUFamily2_v1
    {
        MTLFeatureSet_iOS_GPUFamily2_v1, Version(2, 1),
        //Availability
        {
            true,
            true,
            true,
            true,
            true,
            true,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
        },
        //Limits
        {
            31,
            31,
            31,
            16,
            31,
            4000,
            512,
            16352,
            16,
            (size_t)-1,
            60,
            60,
            0,
            0,
            256000000,
            4,
            4096,
            4096,
            4096,
            2048,
            2048,
            64,
            64,
            8,
            511,
            32,
            65528,
        },
        //Capabilities
        {
            MetalFeatureSetCapability::FILTER,
            MetalFeatureSetCapability::ALL,
            MetalFeatureSetCapability::FILTER | MetalFeatureSetCapability::COLOR | MetalFeatureSetCapability::MSAA | MetalFeatureSetCapability::RESOLVE | MetalFeatureSetCapability::BLEND,
            MetalFeatureSetCapability::ALL,
            MetalFeatureSetCapability::WRITE | MetalFeatureSetCapability::COLOR | MetalFeatureSetCapability::MSAA,
            MetalFeatureSetCapability::FILTER | MetalFeatureSetCapability::WRITE | MetalFeatureSetCapability::COLOR | MetalFeatureSetCapability::MSAA | MetalFeatureSetCapability::BLEND,
            MetalFeatureSetCapability::WRITE | MetalFeatureSetCapability::COLOR | MetalFeatureSetCapability::MSAA,
            MetalFeatureSetCapability::ALL,
            MetalFeatureSetCapability::ALL,
            MetalFeatureSetCapability::FILTER | MetalFeatureSetCapability::COLOR | MetalFeatureSetCapability::MSAA | MetalFeatureSetCapability::RESOLVE | MetalFeatureSetCapability::BLEND,
            MetalFeatureSetCapability::ALL,
            MetalFeatureSetCapability::WRITE | MetalFeatureSetCapability::COLOR | MetalFeatureSetCapability::MSAA,
            MetalFeatureSetCapability::FILTER | MetalFeatureSetCapability::COLOR | MetalFeatureSetCapability::MSAA | MetalFeatureSetCapability::RESOLVE | MetalFeatureSetCapability::BLEND,
            MetalFeatureSetCapability::COLOR,
            MetalFeatureSetCapability::COLOR | MetalFeatureSetCapability::MSAA,
            MetalFeatureSetCapability::FILTER | MetalFeatureSetCapability::WRITE | MetalFeatureSetCapability::COLOR | MetalFeatureSetCapability::MSAA | MetalFeatureSetCapability::BLEND,
            MetalFeatureSetCapability::WRITE | MetalFeatureSetCapability::COLOR | MetalFeatureSetCapability::MSAA,
            MetalFeatureSetCapability::ALL,
            MetalFeatureSetCapability::ALL,
            MetalFeatureSetCapability::FILTER | MetalFeatureSetCapability::COLOR | MetalFeatureSetCapability::MSAA | MetalFeatureSetCapability::RESOLVE | MetalFeatureSetCapability::BLEND,
            MetalFeatureSetCapability::ALL,
            MetalFeatureSetCapability::WRITE | MetalFeatureSetCapability::COLOR | MetalFeatureSetCapability::MSAA,
            MetalFeatureSetCapability::ALL,
            MetalFeatureSetCapability::FILTER | MetalFeatureSetCapability::COLOR | MetalFeatureSetCapability::MSAA | MetalFeatureSetCapability::RESOLVE | MetalFeatureSetCapability::BLEND,
            MetalFeatureSetCapability::FILTER | MetalFeatureSetCapability::COLOR | MetalFeatureSetCapability::MSAA | MetalFeatureSetCapability::RESOLVE | MetalFeatureSetCapability::BLEND,
            MetalFeatureSetCapability::COLOR | MetalFeatureSetCapability::MSAA,
            MetalFeatureSetCapability::FILTER | MetalFeatureSetCapability::COLOR | MetalFeatureSetCapability::MSAA | MetalFeatureSetCapability::RESOLVE | MetalFeatureSetCapability::BLEND,
            MetalFeatureSetCapability::FILTER | MetalFeatureSetCapability::COLOR | MetalFeatureSetCapability::MSAA | MetalFeatureSetCapability::RESOLVE | MetalFeatureSetCapability::BLEND,
            MetalFeatureSetCapability::COLOR,
            MetalFeatureSetCapability::COLOR,
            MetalFeatureSetCapability::FILTER | MetalFeatureSetCapability::WRITE | MetalFeatureSetCapability::COLOR | MetalFeatureSetCapability::MSAA | MetalFeatureSetCapability::BLEND,
            MetalFeatureSetCapability::WRITE | MetalFeatureSetCapability::COLOR | MetalFeatureSetCapability::MSAA,
            MetalFeatureSetCapability::ALL,
            MetalFeatureSetCapability::COLOR,
            MetalFeatureSetCapability::COLOR,
            MetalFeatureSetCapability::FILTER,
            MetalFeatureSetCapability::FILTER,
            MetalFeatureSetCapability::FILTER,
            MetalFeatureSetCapability::NONE,
            MetalFeatureSetCapability::FILTER,
            MetalFeatureSetCapability::NONE,
            MetalFeatureSetCapability::MSAA,
            MetalFeatureSetCapability::MSAA,
            MetalFeatureSetCapability::NONE,
            MetalFeatureSetCapability::MSAA,
            MetalFeatureSetCapability::NONE,
            MetalFeatureSetCapability::MSAA,
            MetalFeatureSetCapability::NONE,
        },
    },
#endif
#if FINJIN_TARGET_PLATFORM == FINJIN_TARGET_PLATFORM_IOS
    //iOS_GPUFamily1_v2
    {
        MTLFeatureSet_iOS_GPUFamily1_v2, Version(1, 2),
        //Availability
        {
            true,
            false,
            true,
            true,
            true,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
        },
        //Limits
        {
            31,
            31,
            31,
            16,
            31,
            4000,
            512,
            16352,
            16,
            (size_t)-1,
            60,
            60,
            0,
            0,
            256000000,
            4,
            8192,
            8192,
            8192,
            2048,
            2048,
            64,
            64,
            4,
            511,
            16,
            65528,
        },
        //Capabilities
        {
            MetalFeatureSetCapability::FILTER,
            MetalFeatureSetCapability::ALL,
            MetalFeatureSetCapability::FILTER | MetalFeatureSetCapability::COLOR | MetalFeatureSetCapability::MSAA | MetalFeatureSetCapability::RESOLVE | MetalFeatureSetCapability::BLEND,
            MetalFeatureSetCapability::FILTER | MetalFeatureSetCapability::WRITE | MetalFeatureSetCapability::COLOR | MetalFeatureSetCapability::MSAA | MetalFeatureSetCapability::BLEND,
            MetalFeatureSetCapability::WRITE | MetalFeatureSetCapability::COLOR | MetalFeatureSetCapability::MSAA,
            MetalFeatureSetCapability::FILTER | MetalFeatureSetCapability::WRITE | MetalFeatureSetCapability::COLOR | MetalFeatureSetCapability::MSAA | MetalFeatureSetCapability::BLEND,
            MetalFeatureSetCapability::WRITE | MetalFeatureSetCapability::COLOR | MetalFeatureSetCapability::MSAA,
            MetalFeatureSetCapability::ALL,
            MetalFeatureSetCapability::ALL,
            MetalFeatureSetCapability::FILTER | MetalFeatureSetCapability::COLOR | MetalFeatureSetCapability::MSAA | MetalFeatureSetCapability::RESOLVE | MetalFeatureSetCapability::BLEND,
            MetalFeatureSetCapability::FILTER | MetalFeatureSetCapability::WRITE | MetalFeatureSetCapability::COLOR | MetalFeatureSetCapability::MSAA | MetalFeatureSetCapability::BLEND,
            MetalFeatureSetCapability::WRITE | MetalFeatureSetCapability::COLOR | MetalFeatureSetCapability::MSAA,
            MetalFeatureSetCapability::FILTER | MetalFeatureSetCapability::COLOR | MetalFeatureSetCapability::MSAA | MetalFeatureSetCapability::RESOLVE | MetalFeatureSetCapability::BLEND,
            MetalFeatureSetCapability::WRITE | MetalFeatureSetCapability::COLOR,
            MetalFeatureSetCapability::WRITE | MetalFeatureSetCapability::COLOR | MetalFeatureSetCapability::MSAA,
            MetalFeatureSetCapability::FILTER | MetalFeatureSetCapability::WRITE | MetalFeatureSetCapability::COLOR | MetalFeatureSetCapability::MSAA | MetalFeatureSetCapability::BLEND,
            MetalFeatureSetCapability::WRITE | MetalFeatureSetCapability::COLOR | MetalFeatureSetCapability::MSAA,
            MetalFeatureSetCapability::ALL,
            MetalFeatureSetCapability::ALL,
            MetalFeatureSetCapability::FILTER | MetalFeatureSetCapability::COLOR | MetalFeatureSetCapability::MSAA | MetalFeatureSetCapability::RESOLVE | MetalFeatureSetCapability::BLEND,
            MetalFeatureSetCapability::FILTER | MetalFeatureSetCapability::WRITE | MetalFeatureSetCapability::COLOR | MetalFeatureSetCapability::MSAA | MetalFeatureSetCapability::BLEND,
            MetalFeatureSetCapability::WRITE | MetalFeatureSetCapability::COLOR | MetalFeatureSetCapability::MSAA,
            MetalFeatureSetCapability::ALL,
            MetalFeatureSetCapability::FILTER | MetalFeatureSetCapability::COLOR | MetalFeatureSetCapability::MSAA | MetalFeatureSetCapability::RESOLVE | MetalFeatureSetCapability::BLEND,
            MetalFeatureSetCapability::FILTER | MetalFeatureSetCapability::COLOR | MetalFeatureSetCapability::MSAA | MetalFeatureSetCapability::RESOLVE | MetalFeatureSetCapability::BLEND,
            MetalFeatureSetCapability::COLOR | MetalFeatureSetCapability::MSAA,
            MetalFeatureSetCapability::FILTER | MetalFeatureSetCapability::COLOR | MetalFeatureSetCapability::MSAA | MetalFeatureSetCapability::RESOLVE | MetalFeatureSetCapability::BLEND,
            MetalFeatureSetCapability::FILTER | MetalFeatureSetCapability::COLOR | MetalFeatureSetCapability::MSAA | MetalFeatureSetCapability::RESOLVE | MetalFeatureSetCapability::BLEND,
            MetalFeatureSetCapability::WRITE | MetalFeatureSetCapability::COLOR,
            MetalFeatureSetCapability::WRITE | MetalFeatureSetCapability::COLOR,
            MetalFeatureSetCapability::FILTER | MetalFeatureSetCapability::WRITE | MetalFeatureSetCapability::COLOR | MetalFeatureSetCapability::MSAA | MetalFeatureSetCapability::BLEND,
            MetalFeatureSetCapability::WRITE | MetalFeatureSetCapability::COLOR | MetalFeatureSetCapability::MSAA,
            MetalFeatureSetCapability::ALL,
            MetalFeatureSetCapability::WRITE | MetalFeatureSetCapability::COLOR,
            MetalFeatureSetCapability::WRITE | MetalFeatureSetCapability::COLOR,
            MetalFeatureSetCapability::FILTER,
            MetalFeatureSetCapability::FILTER,
            MetalFeatureSetCapability::NONE,
            MetalFeatureSetCapability::NONE,
            MetalFeatureSetCapability::FILTER,
            MetalFeatureSetCapability::NONE,
            MetalFeatureSetCapability::MSAA,
            MetalFeatureSetCapability::MSAA,
            MetalFeatureSetCapability::NONE,
            MetalFeatureSetCapability::MSAA,
            MetalFeatureSetCapability::NONE,
            MetalFeatureSetCapability::MSAA,
            MetalFeatureSetCapability::NONE,
        },
    },
#endif
#if FINJIN_TARGET_PLATFORM == FINJIN_TARGET_PLATFORM_IOS
    //iOS_GPUFamily2_v2
    {
        MTLFeatureSet_iOS_GPUFamily2_v2, Version(2, 2),
        //Availability
        {
            true,
            true,
            true,
            true,
            true,
            true,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
        },
        //Limits
        {
            31,
            31,
            31,
            16,
            31,
            4000,
            512,
            16352,
            16,
            (size_t)-1,
            60,
            60,
            0,
            0,
            256000000,
            4,
            8192,
            8192,
            8192,
            2048,
            2048,
            64,
            64,
            8,
            511,
            32,
            65528,
        },
        //Capabilities
        {
            MetalFeatureSetCapability::FILTER,
            MetalFeatureSetCapability::ALL,
            MetalFeatureSetCapability::FILTER | MetalFeatureSetCapability::COLOR | MetalFeatureSetCapability::MSAA | MetalFeatureSetCapability::RESOLVE | MetalFeatureSetCapability::BLEND,
            MetalFeatureSetCapability::ALL,
            MetalFeatureSetCapability::WRITE | MetalFeatureSetCapability::COLOR | MetalFeatureSetCapability::MSAA,
            MetalFeatureSetCapability::FILTER | MetalFeatureSetCapability::WRITE | MetalFeatureSetCapability::COLOR | MetalFeatureSetCapability::MSAA | MetalFeatureSetCapability::BLEND,
            MetalFeatureSetCapability::WRITE | MetalFeatureSetCapability::COLOR | MetalFeatureSetCapability::MSAA,
            MetalFeatureSetCapability::ALL,
            MetalFeatureSetCapability::ALL,
            MetalFeatureSetCapability::FILTER | MetalFeatureSetCapability::COLOR | MetalFeatureSetCapability::MSAA | MetalFeatureSetCapability::RESOLVE | MetalFeatureSetCapability::BLEND,
            MetalFeatureSetCapability::ALL,
            MetalFeatureSetCapability::WRITE | MetalFeatureSetCapability::COLOR | MetalFeatureSetCapability::MSAA,
            MetalFeatureSetCapability::FILTER | MetalFeatureSetCapability::COLOR | MetalFeatureSetCapability::MSAA | MetalFeatureSetCapability::RESOLVE | MetalFeatureSetCapability::BLEND,
            MetalFeatureSetCapability::WRITE | MetalFeatureSetCapability::COLOR,
            MetalFeatureSetCapability::WRITE | MetalFeatureSetCapability::COLOR | MetalFeatureSetCapability::MSAA,
            MetalFeatureSetCapability::FILTER | MetalFeatureSetCapability::WRITE | MetalFeatureSetCapability::COLOR | MetalFeatureSetCapability::MSAA | MetalFeatureSetCapability::BLEND,
            MetalFeatureSetCapability::WRITE | MetalFeatureSetCapability::COLOR | MetalFeatureSetCapability::MSAA,
            MetalFeatureSetCapability::ALL,
            MetalFeatureSetCapability::ALL,
            MetalFeatureSetCapability::FILTER | MetalFeatureSetCapability::COLOR | MetalFeatureSetCapability::MSAA | MetalFeatureSetCapability::RESOLVE | MetalFeatureSetCapability::BLEND,
            MetalFeatureSetCapability::ALL,
            MetalFeatureSetCapability::WRITE | MetalFeatureSetCapability::COLOR | MetalFeatureSetCapability::MSAA,
            MetalFeatureSetCapability::ALL,
            MetalFeatureSetCapability::FILTER | MetalFeatureSetCapability::COLOR | MetalFeatureSetCapability::MSAA | MetalFeatureSetCapability::RESOLVE | MetalFeatureSetCapability::BLEND,
            MetalFeatureSetCapability::FILTER | MetalFeatureSetCapability::COLOR | MetalFeatureSetCapability::MSAA | MetalFeatureSetCapability::RESOLVE | MetalFeatureSetCapability::BLEND,
            MetalFeatureSetCapability::COLOR | MetalFeatureSetCapability::MSAA,
            MetalFeatureSetCapability::FILTER | MetalFeatureSetCapability::COLOR | MetalFeatureSetCapability::MSAA | MetalFeatureSetCapability::RESOLVE | MetalFeatureSetCapability::BLEND,
            MetalFeatureSetCapability::FILTER | MetalFeatureSetCapability::COLOR | MetalFeatureSetCapability::MSAA | MetalFeatureSetCapability::RESOLVE | MetalFeatureSetCapability::BLEND,
            MetalFeatureSetCapability::WRITE | MetalFeatureSetCapability::COLOR,
            MetalFeatureSetCapability::WRITE | MetalFeatureSetCapability::COLOR,
            MetalFeatureSetCapability::FILTER | MetalFeatureSetCapability::WRITE | MetalFeatureSetCapability::COLOR | MetalFeatureSetCapability::MSAA | MetalFeatureSetCapability::BLEND,
            MetalFeatureSetCapability::WRITE | MetalFeatureSetCapability::COLOR | MetalFeatureSetCapability::MSAA,
            MetalFeatureSetCapability::ALL,
            MetalFeatureSetCapability::WRITE | MetalFeatureSetCapability::COLOR,
            MetalFeatureSetCapability::WRITE | MetalFeatureSetCapability::COLOR,
            MetalFeatureSetCapability::FILTER,
            MetalFeatureSetCapability::FILTER,
            MetalFeatureSetCapability::FILTER,
            MetalFeatureSetCapability::NONE,
            MetalFeatureSetCapability::FILTER,
            MetalFeatureSetCapability::NONE,
            MetalFeatureSetCapability::MSAA,
            MetalFeatureSetCapability::MSAA,
            MetalFeatureSetCapability::NONE,
            MetalFeatureSetCapability::MSAA,
            MetalFeatureSetCapability::NONE,
            MetalFeatureSetCapability::MSAA,
            MetalFeatureSetCapability::NONE,
        },
    },
#endif
#if FINJIN_TARGET_PLATFORM == FINJIN_TARGET_PLATFORM_IOS
    //iOS_GPUFamily3_v1
    {
        MTLFeatureSet_iOS_GPUFamily3_v1, Version(3, 1),
        //Availability
        {
            true,
            true,
            true,
            true,
            true,
            true,
            false,
            true,
            true,
            true,
            true,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            true,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
        },
        //Limits
        {
            31,
            31,
            31,
            16,
            31,
            4000,
            512,
            16000,
            16,
            (size_t)-1,
            60,
            60,
            0,
            0,
            256000000,
            4,
            16384,
            16384,
            16384,
            2048,
            2048,
            16,
            16,
            8,
            511,
            32,
            65528,
        },
        //Capabilities
        {
            MetalFeatureSetCapability::FILTER,
            MetalFeatureSetCapability::ALL,
            MetalFeatureSetCapability::ALL,
            MetalFeatureSetCapability::ALL,
            MetalFeatureSetCapability::WRITE | MetalFeatureSetCapability::COLOR | MetalFeatureSetCapability::MSAA,
            MetalFeatureSetCapability::FILTER | MetalFeatureSetCapability::WRITE | MetalFeatureSetCapability::COLOR | MetalFeatureSetCapability::MSAA | MetalFeatureSetCapability::BLEND,
            MetalFeatureSetCapability::WRITE | MetalFeatureSetCapability::COLOR | MetalFeatureSetCapability::MSAA,
            MetalFeatureSetCapability::ALL,
            MetalFeatureSetCapability::ALL,
            MetalFeatureSetCapability::ALL,
            MetalFeatureSetCapability::ALL,
            MetalFeatureSetCapability::WRITE | MetalFeatureSetCapability::COLOR | MetalFeatureSetCapability::MSAA,
            MetalFeatureSetCapability::FILTER | MetalFeatureSetCapability::COLOR | MetalFeatureSetCapability::MSAA | MetalFeatureSetCapability::RESOLVE | MetalFeatureSetCapability::BLEND,
            MetalFeatureSetCapability::WRITE | MetalFeatureSetCapability::COLOR,
            MetalFeatureSetCapability::WRITE | MetalFeatureSetCapability::COLOR | MetalFeatureSetCapability::MSAA,
            MetalFeatureSetCapability::FILTER | MetalFeatureSetCapability::WRITE | MetalFeatureSetCapability::COLOR | MetalFeatureSetCapability::MSAA | MetalFeatureSetCapability::BLEND,
            MetalFeatureSetCapability::WRITE | MetalFeatureSetCapability::COLOR | MetalFeatureSetCapability::MSAA,
            MetalFeatureSetCapability::ALL,
            MetalFeatureSetCapability::ALL,
            MetalFeatureSetCapability::ALL,
            MetalFeatureSetCapability::ALL,
            MetalFeatureSetCapability::WRITE | MetalFeatureSetCapability::COLOR | MetalFeatureSetCapability::MSAA,
            MetalFeatureSetCapability::ALL,
            MetalFeatureSetCapability::ALL,
            MetalFeatureSetCapability::ALL,
            MetalFeatureSetCapability::WRITE | MetalFeatureSetCapability::COLOR | MetalFeatureSetCapability::MSAA,
            MetalFeatureSetCapability::ALL,
            MetalFeatureSetCapability::ALL,
            MetalFeatureSetCapability::WRITE | MetalFeatureSetCapability::COLOR,
            MetalFeatureSetCapability::WRITE | MetalFeatureSetCapability::COLOR,
            MetalFeatureSetCapability::FILTER | MetalFeatureSetCapability::WRITE | MetalFeatureSetCapability::COLOR | MetalFeatureSetCapability::MSAA | MetalFeatureSetCapability::BLEND,
            MetalFeatureSetCapability::WRITE | MetalFeatureSetCapability::COLOR | MetalFeatureSetCapability::MSAA,
            MetalFeatureSetCapability::ALL,
            MetalFeatureSetCapability::WRITE | MetalFeatureSetCapability::COLOR,
            MetalFeatureSetCapability::WRITE | MetalFeatureSetCapability::COLOR,
            MetalFeatureSetCapability::FILTER,
            MetalFeatureSetCapability::FILTER,
            MetalFeatureSetCapability::FILTER,
            MetalFeatureSetCapability::NONE,
            MetalFeatureSetCapability::FILTER,
            MetalFeatureSetCapability::NONE,
            MetalFeatureSetCapability::MSAA | MetalFeatureSetCapability::RESOLVE,
            MetalFeatureSetCapability::MSAA,
            MetalFeatureSetCapability::NONE,
            MetalFeatureSetCapability::MSAA | MetalFeatureSetCapability::RESOLVE,
            MetalFeatureSetCapability::NONE,
            MetalFeatureSetCapability::MSAA,
            MetalFeatureSetCapability::NONE,
        },
    },
#endif
#if FINJIN_TARGET_PLATFORM == FINJIN_TARGET_PLATFORM_IOS
    //iOS_GPUFamily1_v3
    {
        MTLFeatureSet_iOS_GPUFamily1_v3, Version(1, 3),
        //Availability
        {
            true,
            false,
            true,
            true,
            true,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            true,
            true,
            true,
            false,
            false,
            false,
            true,
            false,
            false,
            false,
            true,
            true,
            false,
            true,
            true,
            true,
            true,
            true,
            false,
            false,
        },
        //Limits
        {
            31,
            31,
            31,
            16,
            31,
            4000,
            512,
            16352,
            16,
            (size_t)-1,
            60,
            60,
            65536,
            0,
            256000000,
            4,
            8192,
            8192,
            8192,
            2048,
            2048,
            64,
            64,
            4,
            511,
            16,
            65528,
        },
        //Capabilities
        {
            MetalFeatureSetCapability::FILTER,
            MetalFeatureSetCapability::ALL,
            MetalFeatureSetCapability::FILTER | MetalFeatureSetCapability::COLOR | MetalFeatureSetCapability::MSAA | MetalFeatureSetCapability::RESOLVE | MetalFeatureSetCapability::BLEND,
            MetalFeatureSetCapability::FILTER | MetalFeatureSetCapability::WRITE | MetalFeatureSetCapability::COLOR | MetalFeatureSetCapability::MSAA | MetalFeatureSetCapability::BLEND,
            MetalFeatureSetCapability::WRITE | MetalFeatureSetCapability::COLOR | MetalFeatureSetCapability::MSAA,
            MetalFeatureSetCapability::FILTER | MetalFeatureSetCapability::WRITE | MetalFeatureSetCapability::COLOR | MetalFeatureSetCapability::MSAA | MetalFeatureSetCapability::BLEND,
            MetalFeatureSetCapability::WRITE | MetalFeatureSetCapability::COLOR | MetalFeatureSetCapability::MSAA,
            MetalFeatureSetCapability::ALL,
            MetalFeatureSetCapability::ALL,
            MetalFeatureSetCapability::FILTER | MetalFeatureSetCapability::COLOR | MetalFeatureSetCapability::MSAA | MetalFeatureSetCapability::RESOLVE | MetalFeatureSetCapability::BLEND,
            MetalFeatureSetCapability::FILTER | MetalFeatureSetCapability::WRITE | MetalFeatureSetCapability::COLOR | MetalFeatureSetCapability::MSAA | MetalFeatureSetCapability::BLEND,
            MetalFeatureSetCapability::WRITE | MetalFeatureSetCapability::COLOR | MetalFeatureSetCapability::MSAA,
            MetalFeatureSetCapability::FILTER | MetalFeatureSetCapability::COLOR | MetalFeatureSetCapability::MSAA | MetalFeatureSetCapability::RESOLVE | MetalFeatureSetCapability::BLEND,
            MetalFeatureSetCapability::WRITE | MetalFeatureSetCapability::COLOR,
            MetalFeatureSetCapability::WRITE | MetalFeatureSetCapability::COLOR | MetalFeatureSetCapability::MSAA,
            MetalFeatureSetCapability::FILTER | MetalFeatureSetCapability::WRITE | MetalFeatureSetCapability::COLOR | MetalFeatureSetCapability::MSAA | MetalFeatureSetCapability::BLEND,
            MetalFeatureSetCapability::WRITE | MetalFeatureSetCapability::COLOR | MetalFeatureSetCapability::MSAA,
            MetalFeatureSetCapability::ALL,
            MetalFeatureSetCapability::ALL,
            MetalFeatureSetCapability::FILTER | MetalFeatureSetCapability::COLOR | MetalFeatureSetCapability::MSAA | MetalFeatureSetCapability::RESOLVE | MetalFeatureSetCapability::BLEND,
            MetalFeatureSetCapability::FILTER | MetalFeatureSetCapability::WRITE | MetalFeatureSetCapability::COLOR | MetalFeatureSetCapability::MSAA | MetalFeatureSetCapability::BLEND,
            MetalFeatureSetCapability::WRITE | MetalFeatureSetCapability::COLOR | MetalFeatureSetCapability::MSAA,
            MetalFeatureSetCapability::ALL,
            MetalFeatureSetCapability::FILTER | MetalFeatureSetCapability::COLOR | MetalFeatureSetCapability::MSAA | MetalFeatureSetCapability::RESOLVE | MetalFeatureSetCapability::BLEND,
            MetalFeatureSetCapability::FILTER | MetalFeatureSetCapability::COLOR | MetalFeatureSetCapability::MSAA | MetalFeatureSetCapability::RESOLVE | MetalFeatureSetCapability::BLEND,
            MetalFeatureSetCapability::COLOR | MetalFeatureSetCapability::MSAA,
            MetalFeatureSetCapability::FILTER | MetalFeatureSetCapability::COLOR | MetalFeatureSetCapability::MSAA | MetalFeatureSetCapability::RESOLVE | MetalFeatureSetCapability::BLEND,
            MetalFeatureSetCapability::FILTER | MetalFeatureSetCapability::COLOR | MetalFeatureSetCapability::MSAA | MetalFeatureSetCapability::RESOLVE | MetalFeatureSetCapability::BLEND,
            MetalFeatureSetCapability::WRITE | MetalFeatureSetCapability::COLOR,
            MetalFeatureSetCapability::WRITE | MetalFeatureSetCapability::COLOR,
            MetalFeatureSetCapability::FILTER | MetalFeatureSetCapability::WRITE | MetalFeatureSetCapability::COLOR | MetalFeatureSetCapability::MSAA | MetalFeatureSetCapability::BLEND,
            MetalFeatureSetCapability::WRITE | MetalFeatureSetCapability::COLOR | MetalFeatureSetCapability::MSAA,
            MetalFeatureSetCapability::ALL,
            MetalFeatureSetCapability::WRITE | MetalFeatureSetCapability::COLOR,
            MetalFeatureSetCapability::WRITE | MetalFeatureSetCapability::COLOR,
            MetalFeatureSetCapability::FILTER,
            MetalFeatureSetCapability::FILTER,
            MetalFeatureSetCapability::NONE,
            MetalFeatureSetCapability::NONE,
            MetalFeatureSetCapability::FILTER,
            MetalFeatureSetCapability::NONE,
            MetalFeatureSetCapability::MSAA,
            MetalFeatureSetCapability::MSAA,
            MetalFeatureSetCapability::NONE,
            MetalFeatureSetCapability::MSAA,
            MetalFeatureSetCapability::NONE,
            MetalFeatureSetCapability::MSAA,
            MetalFeatureSetCapability::NONE,
        },
    },
#endif
#if FINJIN_TARGET_PLATFORM == FINJIN_TARGET_PLATFORM_IOS
    //iOS_GPUFamily2_v3
    {
        MTLFeatureSet_iOS_GPUFamily2_v3, Version(2, 3),
        //Availability
        {
            true,
            true,
            true,
            true,
            true,
            true,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            true,
            true,
            true,
            false,
            false,
            false,
            true,
            false,
            false,
            false,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            false,
            false,
        },
        //Limits
        {
            31,
            31,
            31,
            16,
            31,
            4000,
            512,
            16352,
            16,
            (size_t)-1,
            60,
            60,
            65536,
            0,
            256000000,
            4,
            8192,
            8192,
            8192,
            2048,
            2048,
            64,
            64,
            8,
            511,
            32,
            65528,
        },
        //Capabilities
        {
            MetalFeatureSetCapability::FILTER,
            MetalFeatureSetCapability::ALL,
            MetalFeatureSetCapability::ALL,
            MetalFeatureSetCapability::ALL,
            MetalFeatureSetCapability::WRITE | MetalFeatureSetCapability::COLOR | MetalFeatureSetCapability::MSAA,
            MetalFeatureSetCapability::FILTER | MetalFeatureSetCapability::WRITE | MetalFeatureSetCapability::COLOR | MetalFeatureSetCapability::MSAA | MetalFeatureSetCapability::BLEND,
            MetalFeatureSetCapability::WRITE | MetalFeatureSetCapability::COLOR | MetalFeatureSetCapability::MSAA,
            MetalFeatureSetCapability::ALL,
            MetalFeatureSetCapability::ALL,
            MetalFeatureSetCapability::ALL,
            MetalFeatureSetCapability::ALL,
            MetalFeatureSetCapability::WRITE | MetalFeatureSetCapability::COLOR | MetalFeatureSetCapability::MSAA,
            MetalFeatureSetCapability::FILTER | MetalFeatureSetCapability::COLOR | MetalFeatureSetCapability::MSAA | MetalFeatureSetCapability::RESOLVE | MetalFeatureSetCapability::BLEND,
            MetalFeatureSetCapability::WRITE | MetalFeatureSetCapability::COLOR,
            MetalFeatureSetCapability::WRITE | MetalFeatureSetCapability::COLOR | MetalFeatureSetCapability::MSAA,
            MetalFeatureSetCapability::FILTER | MetalFeatureSetCapability::WRITE | MetalFeatureSetCapability::COLOR | MetalFeatureSetCapability::MSAA | MetalFeatureSetCapability::BLEND,
            MetalFeatureSetCapability::WRITE | MetalFeatureSetCapability::COLOR | MetalFeatureSetCapability::MSAA,
            MetalFeatureSetCapability::ALL,
            MetalFeatureSetCapability::ALL,
            MetalFeatureSetCapability::ALL,
            MetalFeatureSetCapability::ALL,
            MetalFeatureSetCapability::WRITE | MetalFeatureSetCapability::COLOR | MetalFeatureSetCapability::MSAA,
            MetalFeatureSetCapability::ALL,
            MetalFeatureSetCapability::ALL,
            MetalFeatureSetCapability::FILTER | MetalFeatureSetCapability::COLOR | MetalFeatureSetCapability::MSAA | MetalFeatureSetCapability::RESOLVE | MetalFeatureSetCapability::BLEND,
            MetalFeatureSetCapability::COLOR | MetalFeatureSetCapability::MSAA,
            MetalFeatureSetCapability::FILTER | MetalFeatureSetCapability::COLOR | MetalFeatureSetCapability::MSAA | MetalFeatureSetCapability::RESOLVE | MetalFeatureSetCapability::BLEND,
            MetalFeatureSetCapability::FILTER | MetalFeatureSetCapability::COLOR | MetalFeatureSetCapability::MSAA | MetalFeatureSetCapability::RESOLVE | MetalFeatureSetCapability::BLEND,
            MetalFeatureSetCapability::WRITE | MetalFeatureSetCapability::COLOR,
            MetalFeatureSetCapability::WRITE | MetalFeatureSetCapability::COLOR,
            MetalFeatureSetCapability::FILTER | MetalFeatureSetCapability::WRITE | MetalFeatureSetCapability::COLOR | MetalFeatureSetCapability::MSAA | MetalFeatureSetCapability::BLEND,
            MetalFeatureSetCapability::WRITE | MetalFeatureSetCapability::COLOR | MetalFeatureSetCapability::MSAA,
            MetalFeatureSetCapability::ALL,
            MetalFeatureSetCapability::WRITE | MetalFeatureSetCapability::COLOR,
            MetalFeatureSetCapability::WRITE | MetalFeatureSetCapability::COLOR,
            MetalFeatureSetCapability::FILTER,
            MetalFeatureSetCapability::FILTER,
            MetalFeatureSetCapability::FILTER,
            MetalFeatureSetCapability::NONE,
            MetalFeatureSetCapability::FILTER,
            MetalFeatureSetCapability::NONE,
            MetalFeatureSetCapability::MSAA,
            MetalFeatureSetCapability::MSAA,
            MetalFeatureSetCapability::NONE,
            MetalFeatureSetCapability::MSAA,
            MetalFeatureSetCapability::NONE,
            MetalFeatureSetCapability::MSAA,
            MetalFeatureSetCapability::NONE,
        },
    },
#endif
#if FINJIN_TARGET_PLATFORM == FINJIN_TARGET_PLATFORM_IOS
    //iOS_GPUFamily3_v2
    {
        MTLFeatureSet_iOS_GPUFamily3_v2, Version(3, 2),
        //Availability
        {
            true,
            true,
            true,
            true,
            true,
            true,
            false,
            true,
            true,
            true,
            true,
            false,
            false,
            false,
            true,
            true,
            true,
            true,
            true,
            false,
            true,
            true,
            false,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            false,
            false,
        },
        //Limits
        {
            31,
            31,
            31,
            16,
            31,
            4000,
            512,
            16000,
            16,
            (size_t)-1,
            60,
            60,
            65536,
            16,
            256000000,
            4,
            16384,
            16384,
            16384,
            2048,
            2048,
            16,
            16,
            8,
            511,
            32,
            65528,
        },
        //Capabilities
        {
            MetalFeatureSetCapability::FILTER,
            MetalFeatureSetCapability::ALL,
            MetalFeatureSetCapability::ALL,
            MetalFeatureSetCapability::ALL,
            MetalFeatureSetCapability::WRITE | MetalFeatureSetCapability::COLOR | MetalFeatureSetCapability::MSAA,
            MetalFeatureSetCapability::FILTER | MetalFeatureSetCapability::WRITE | MetalFeatureSetCapability::COLOR | MetalFeatureSetCapability::MSAA | MetalFeatureSetCapability::BLEND,
            MetalFeatureSetCapability::WRITE | MetalFeatureSetCapability::COLOR | MetalFeatureSetCapability::MSAA,
            MetalFeatureSetCapability::ALL,
            MetalFeatureSetCapability::ALL,
            MetalFeatureSetCapability::ALL,
            MetalFeatureSetCapability::ALL,
            MetalFeatureSetCapability::WRITE | MetalFeatureSetCapability::COLOR | MetalFeatureSetCapability::MSAA,
            MetalFeatureSetCapability::FILTER | MetalFeatureSetCapability::COLOR | MetalFeatureSetCapability::MSAA | MetalFeatureSetCapability::RESOLVE | MetalFeatureSetCapability::BLEND,
            MetalFeatureSetCapability::WRITE | MetalFeatureSetCapability::COLOR,
            MetalFeatureSetCapability::WRITE | MetalFeatureSetCapability::COLOR | MetalFeatureSetCapability::MSAA,
            MetalFeatureSetCapability::FILTER | MetalFeatureSetCapability::WRITE | MetalFeatureSetCapability::COLOR | MetalFeatureSetCapability::MSAA | MetalFeatureSetCapability::BLEND,
            MetalFeatureSetCapability::WRITE | MetalFeatureSetCapability::COLOR | MetalFeatureSetCapability::MSAA,
            MetalFeatureSetCapability::ALL,
            MetalFeatureSetCapability::ALL,
            MetalFeatureSetCapability::ALL,
            MetalFeatureSetCapability::ALL,
            MetalFeatureSetCapability::WRITE | MetalFeatureSetCapability::COLOR | MetalFeatureSetCapability::MSAA,
            MetalFeatureSetCapability::ALL,
            MetalFeatureSetCapability::ALL,
            MetalFeatureSetCapability::ALL,
            MetalFeatureSetCapability::WRITE | MetalFeatureSetCapability::COLOR | MetalFeatureSetCapability::MSAA,
            MetalFeatureSetCapability::ALL,
            MetalFeatureSetCapability::ALL,
            MetalFeatureSetCapability::WRITE | MetalFeatureSetCapability::COLOR,
            MetalFeatureSetCapability::WRITE | MetalFeatureSetCapability::COLOR,
            MetalFeatureSetCapability::FILTER | MetalFeatureSetCapability::WRITE | MetalFeatureSetCapability::COLOR | MetalFeatureSetCapability::MSAA | MetalFeatureSetCapability::BLEND,
            MetalFeatureSetCapability::WRITE | MetalFeatureSetCapability::COLOR | MetalFeatureSetCapability::MSAA,
            MetalFeatureSetCapability::ALL,
            MetalFeatureSetCapability::WRITE | MetalFeatureSetCapability::COLOR,
            MetalFeatureSetCapability::WRITE | MetalFeatureSetCapability::COLOR,
            MetalFeatureSetCapability::FILTER,
            MetalFeatureSetCapability::FILTER,
            MetalFeatureSetCapability::FILTER,
            MetalFeatureSetCapability::NONE,
            MetalFeatureSetCapability::FILTER,
            MetalFeatureSetCapability::NONE,
            MetalFeatureSetCapability::MSAA | MetalFeatureSetCapability::RESOLVE,
            MetalFeatureSetCapability::MSAA,
            MetalFeatureSetCapability::NONE,
            MetalFeatureSetCapability::MSAA | MetalFeatureSetCapability::RESOLVE,
            MetalFeatureSetCapability::NONE,
            MetalFeatureSetCapability::MSAA,
            MetalFeatureSetCapability::ALL,
        },
    },
#endif
#if FINJIN_TARGET_PLATFORM == FINJIN_TARGET_PLATFORM_TVOS
    //tvOS_GPUFamily1_v1
    {
        MTLFeatureSet_tvOS_GPUFamily1_v1, Version(1, 1),
        //Availability
        {
            true,
            true,
            true,
            true,
            true,
            true,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
        },
        //Limits
        {
            31,
            31,
            31,
            16,
            31,
            4000,
            512,
            16352,
            16,
            (size_t)-1,
            60,
            60,
            0,
            0,
            256000000,
            4,
            8192,
            8192,
            8192,
            2048,
            2048,
            64,
            64,
            8,
            511,
            32,
            65528,
        },
        //Capabilities
        {
            MetalFeatureSetCapability::FILTER,
            MetalFeatureSetCapability::ALL,
            MetalFeatureSetCapability::FILTER | MetalFeatureSetCapability::COLOR | MetalFeatureSetCapability::MSAA | MetalFeatureSetCapability::RESOLVE | MetalFeatureSetCapability::BLEND,
            MetalFeatureSetCapability::ALL,
            MetalFeatureSetCapability::WRITE | MetalFeatureSetCapability::COLOR | MetalFeatureSetCapability::MSAA,
            MetalFeatureSetCapability::FILTER | MetalFeatureSetCapability::WRITE | MetalFeatureSetCapability::COLOR | MetalFeatureSetCapability::MSAA | MetalFeatureSetCapability::BLEND,
            MetalFeatureSetCapability::WRITE | MetalFeatureSetCapability::COLOR | MetalFeatureSetCapability::MSAA,
            MetalFeatureSetCapability::ALL,
            MetalFeatureSetCapability::ALL,
            MetalFeatureSetCapability::FILTER | MetalFeatureSetCapability::COLOR | MetalFeatureSetCapability::MSAA | MetalFeatureSetCapability::RESOLVE | MetalFeatureSetCapability::BLEND,
            MetalFeatureSetCapability::ALL,
            MetalFeatureSetCapability::WRITE | MetalFeatureSetCapability::COLOR | MetalFeatureSetCapability::MSAA,
            MetalFeatureSetCapability::FILTER | MetalFeatureSetCapability::COLOR | MetalFeatureSetCapability::MSAA | MetalFeatureSetCapability::RESOLVE | MetalFeatureSetCapability::BLEND,
            MetalFeatureSetCapability::WRITE | MetalFeatureSetCapability::COLOR,
            MetalFeatureSetCapability::WRITE | MetalFeatureSetCapability::COLOR | MetalFeatureSetCapability::MSAA,
            MetalFeatureSetCapability::FILTER | MetalFeatureSetCapability::WRITE | MetalFeatureSetCapability::COLOR | MetalFeatureSetCapability::MSAA | MetalFeatureSetCapability::BLEND,
            MetalFeatureSetCapability::WRITE | MetalFeatureSetCapability::COLOR | MetalFeatureSetCapability::MSAA,
            MetalFeatureSetCapability::ALL,
            MetalFeatureSetCapability::ALL,
            MetalFeatureSetCapability::FILTER | MetalFeatureSetCapability::COLOR | MetalFeatureSetCapability::MSAA | MetalFeatureSetCapability::RESOLVE | MetalFeatureSetCapability::BLEND,
            MetalFeatureSetCapability::ALL,
            MetalFeatureSetCapability::WRITE | MetalFeatureSetCapability::COLOR | MetalFeatureSetCapability::MSAA,
            MetalFeatureSetCapability::ALL,
            MetalFeatureSetCapability::FILTER | MetalFeatureSetCapability::COLOR | MetalFeatureSetCapability::MSAA | MetalFeatureSetCapability::RESOLVE | MetalFeatureSetCapability::BLEND,
            MetalFeatureSetCapability::FILTER | MetalFeatureSetCapability::COLOR | MetalFeatureSetCapability::MSAA | MetalFeatureSetCapability::RESOLVE | MetalFeatureSetCapability::BLEND,
            MetalFeatureSetCapability::COLOR | MetalFeatureSetCapability::MSAA,
            MetalFeatureSetCapability::FILTER | MetalFeatureSetCapability::COLOR | MetalFeatureSetCapability::MSAA | MetalFeatureSetCapability::RESOLVE | MetalFeatureSetCapability::BLEND,
            MetalFeatureSetCapability::FILTER | MetalFeatureSetCapability::COLOR | MetalFeatureSetCapability::MSAA | MetalFeatureSetCapability::RESOLVE | MetalFeatureSetCapability::BLEND,
            MetalFeatureSetCapability::WRITE | MetalFeatureSetCapability::COLOR,
            MetalFeatureSetCapability::WRITE | MetalFeatureSetCapability::COLOR,
            MetalFeatureSetCapability::FILTER | MetalFeatureSetCapability::WRITE | MetalFeatureSetCapability::COLOR | MetalFeatureSetCapability::MSAA | MetalFeatureSetCapability::BLEND,
            MetalFeatureSetCapability::WRITE | MetalFeatureSetCapability::COLOR | MetalFeatureSetCapability::MSAA,
            MetalFeatureSetCapability::ALL,
            MetalFeatureSetCapability::WRITE | MetalFeatureSetCapability::COLOR,
            MetalFeatureSetCapability::WRITE | MetalFeatureSetCapability::COLOR,
            MetalFeatureSetCapability::FILTER,
            MetalFeatureSetCapability::FILTER,
            MetalFeatureSetCapability::FILTER,
            MetalFeatureSetCapability::NONE,
            MetalFeatureSetCapability::FILTER,
            MetalFeatureSetCapability::NONE,
            MetalFeatureSetCapability::MSAA,
            MetalFeatureSetCapability::MSAA,
            MetalFeatureSetCapability::NONE,
            MetalFeatureSetCapability::MSAA,
            MetalFeatureSetCapability::NONE,
            MetalFeatureSetCapability::MSAA,
            MetalFeatureSetCapability::NONE,
        },
    },
#endif
#if FINJIN_TARGET_PLATFORM == FINJIN_TARGET_PLATFORM_TVOS
    //tvOS_GPUFamily1_v2
    {
        MTLFeatureSet_tvOS_GPUFamily1_v2, Version(1, 2),
        //Availability
        {
            true,
            true,
            true,
            true,
            true,
            true,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            true,
            true,
            true,
            false,
            false,
            false,
            true,
            false,
            false,
            false,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            false,
            false,
        },
        //Limits
        {
            31,
            31,
            31,
            16,
            31,
            4000,
            512,
            16352,
            16,
            (size_t)-1,
            60,
            60,
            65536,
            0,
            256000000,
            4,
            8192,
            8192,
            8192,
            2048,
            2048,
            64,
            64,
            8,
            511,
            32,
            65528,
        },
        //Capabilities
        {
            MetalFeatureSetCapability::FILTER,
            MetalFeatureSetCapability::ALL,
            MetalFeatureSetCapability::ALL,
            MetalFeatureSetCapability::ALL,
            MetalFeatureSetCapability::WRITE | MetalFeatureSetCapability::COLOR | MetalFeatureSetCapability::MSAA,
            MetalFeatureSetCapability::FILTER | MetalFeatureSetCapability::WRITE | MetalFeatureSetCapability::COLOR | MetalFeatureSetCapability::MSAA | MetalFeatureSetCapability::BLEND,
            MetalFeatureSetCapability::WRITE | MetalFeatureSetCapability::COLOR | MetalFeatureSetCapability::MSAA,
            MetalFeatureSetCapability::ALL,
            MetalFeatureSetCapability::ALL,
            MetalFeatureSetCapability::ALL,
            MetalFeatureSetCapability::ALL,
            MetalFeatureSetCapability::WRITE | MetalFeatureSetCapability::COLOR | MetalFeatureSetCapability::MSAA,
            MetalFeatureSetCapability::FILTER | MetalFeatureSetCapability::COLOR | MetalFeatureSetCapability::MSAA | MetalFeatureSetCapability::RESOLVE | MetalFeatureSetCapability::BLEND,
            MetalFeatureSetCapability::WRITE | MetalFeatureSetCapability::COLOR,
            MetalFeatureSetCapability::WRITE | MetalFeatureSetCapability::COLOR | MetalFeatureSetCapability::MSAA,
            MetalFeatureSetCapability::FILTER | MetalFeatureSetCapability::WRITE | MetalFeatureSetCapability::COLOR | MetalFeatureSetCapability::MSAA | MetalFeatureSetCapability::BLEND,
            MetalFeatureSetCapability::WRITE | MetalFeatureSetCapability::COLOR | MetalFeatureSetCapability::MSAA,
            MetalFeatureSetCapability::ALL,
            MetalFeatureSetCapability::ALL,
            MetalFeatureSetCapability::ALL,
            MetalFeatureSetCapability::ALL,
            MetalFeatureSetCapability::WRITE | MetalFeatureSetCapability::COLOR | MetalFeatureSetCapability::MSAA,
            MetalFeatureSetCapability::ALL,
            MetalFeatureSetCapability::ALL,
            MetalFeatureSetCapability::FILTER | MetalFeatureSetCapability::COLOR | MetalFeatureSetCapability::MSAA | MetalFeatureSetCapability::RESOLVE | MetalFeatureSetCapability::BLEND,
            MetalFeatureSetCapability::COLOR | MetalFeatureSetCapability::MSAA,
            MetalFeatureSetCapability::FILTER | MetalFeatureSetCapability::COLOR | MetalFeatureSetCapability::MSAA | MetalFeatureSetCapability::RESOLVE | MetalFeatureSetCapability::BLEND,
            MetalFeatureSetCapability::FILTER | MetalFeatureSetCapability::COLOR | MetalFeatureSetCapability::MSAA | MetalFeatureSetCapability::RESOLVE | MetalFeatureSetCapability::BLEND,
            MetalFeatureSetCapability::WRITE | MetalFeatureSetCapability::COLOR,
            MetalFeatureSetCapability::WRITE | MetalFeatureSetCapability::COLOR,
            MetalFeatureSetCapability::FILTER | MetalFeatureSetCapability::WRITE | MetalFeatureSetCapability::COLOR | MetalFeatureSetCapability::MSAA | MetalFeatureSetCapability::BLEND,
            MetalFeatureSetCapability::WRITE | MetalFeatureSetCapability::COLOR | MetalFeatureSetCapability::MSAA,
            MetalFeatureSetCapability::ALL,
            MetalFeatureSetCapability::WRITE | MetalFeatureSetCapability::COLOR,
            MetalFeatureSetCapability::WRITE | MetalFeatureSetCapability::COLOR,
            MetalFeatureSetCapability::FILTER,
            MetalFeatureSetCapability::FILTER,
            MetalFeatureSetCapability::FILTER,
            MetalFeatureSetCapability::NONE,
            MetalFeatureSetCapability::FILTER,
            MetalFeatureSetCapability::NONE,
            MetalFeatureSetCapability::MSAA,
            MetalFeatureSetCapability::MSAA,
            MetalFeatureSetCapability::NONE,
            MetalFeatureSetCapability::MSAA,
            MetalFeatureSetCapability::NONE,
            MetalFeatureSetCapability::MSAA,
            MetalFeatureSetCapability::NONE,
        },
    },
#endif
#if FINJIN_TARGET_PLATFORM == FINJIN_TARGET_PLATFORM_MACOS
    //OSX_GPUFamily1_v1
    {
        MTLFeatureSet_OSX_GPUFamily1_v1, Version(1, 1),
        //Availability
        {
            true,
            false,
            false,
            false,
            false,
            false,
            true,
            false,
            true,
            true,
            true,
            true,
            true,
            true,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            true,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
            false,
        },
        //Limits
        {
            31,
            31,
            128,
            16,
            31,
            4000,
            1024,
            32000,
            16,
            64000,
            32,
            128,
            0,
            0,
            256000000,
            256,
            16384,
            16384,
            16384,
            2048,
            2048,
            256,
            0,
            8,
            511,
            (size_t)-1,
            65528,
        },
        //Capabilities
        {
            MetalFeatureSetCapability::FILTER,
            MetalFeatureSetCapability::ALL,
            MetalFeatureSetCapability::NONE,
            MetalFeatureSetCapability::ALL,
            MetalFeatureSetCapability::WRITE | MetalFeatureSetCapability::COLOR | MetalFeatureSetCapability::MSAA,
            MetalFeatureSetCapability::ALL,
            MetalFeatureSetCapability::WRITE | MetalFeatureSetCapability::COLOR | MetalFeatureSetCapability::MSAA,
            MetalFeatureSetCapability::ALL,
            MetalFeatureSetCapability::ALL,
            MetalFeatureSetCapability::NONE,
            MetalFeatureSetCapability::ALL,
            MetalFeatureSetCapability::WRITE | MetalFeatureSetCapability::COLOR | MetalFeatureSetCapability::MSAA,
            MetalFeatureSetCapability::NONE,
            MetalFeatureSetCapability::WRITE | MetalFeatureSetCapability::COLOR | MetalFeatureSetCapability::MSAA,
            MetalFeatureSetCapability::ALL,
            MetalFeatureSetCapability::ALL,
            MetalFeatureSetCapability::WRITE | MetalFeatureSetCapability::COLOR | MetalFeatureSetCapability::MSAA,
            MetalFeatureSetCapability::ALL,
            MetalFeatureSetCapability::ALL,
            MetalFeatureSetCapability::FILTER | MetalFeatureSetCapability::COLOR | MetalFeatureSetCapability::MSAA | MetalFeatureSetCapability::RESOLVE | MetalFeatureSetCapability::BLEND,
            MetalFeatureSetCapability::ALL,
            MetalFeatureSetCapability::WRITE | MetalFeatureSetCapability::COLOR | MetalFeatureSetCapability::MSAA,
            MetalFeatureSetCapability::ALL,
            MetalFeatureSetCapability::FILTER | MetalFeatureSetCapability::COLOR | MetalFeatureSetCapability::MSAA | MetalFeatureSetCapability::RESOLVE | MetalFeatureSetCapability::BLEND,
            MetalFeatureSetCapability::ALL,
            MetalFeatureSetCapability::WRITE | MetalFeatureSetCapability::COLOR | MetalFeatureSetCapability::MSAA,
            MetalFeatureSetCapability::ALL,
            MetalFeatureSetCapability::FILTER,
            MetalFeatureSetCapability::WRITE | MetalFeatureSetCapability::COLOR | MetalFeatureSetCapability::MSAA,
            MetalFeatureSetCapability::ALL,
            MetalFeatureSetCapability::ALL,
            MetalFeatureSetCapability::WRITE | MetalFeatureSetCapability::COLOR | MetalFeatureSetCapability::MSAA,
            MetalFeatureSetCapability::ALL,
            MetalFeatureSetCapability::WRITE | MetalFeatureSetCapability::COLOR | MetalFeatureSetCapability::MSAA,
            MetalFeatureSetCapability::ALL,
            MetalFeatureSetCapability::NONE,
            MetalFeatureSetCapability::NONE,
            MetalFeatureSetCapability::NONE,
            MetalFeatureSetCapability::FILTER,
            MetalFeatureSetCapability::FILTER,
            MetalFeatureSetCapability::NONE,
            MetalFeatureSetCapability::FILTER | MetalFeatureSetCapability::MSAA | MetalFeatureSetCapability::RESOLVE,
            MetalFeatureSetCapability::MSAA,
            MetalFeatureSetCapability::FILTER | MetalFeatureSetCapability::MSAA | MetalFeatureSetCapability::RESOLVE,
            MetalFeatureSetCapability::FILTER | MetalFeatureSetCapability::MSAA | MetalFeatureSetCapability::RESOLVE,
            MetalFeatureSetCapability::MSAA,
            MetalFeatureSetCapability::MSAA,
            MetalFeatureSetCapability::NONE,
        },
    },
#endif
#if FINJIN_TARGET_PLATFORM == FINJIN_TARGET_PLATFORM_MACOS
    //OSX_GPUFamily1_v2
    {
        MTLFeatureSet_OSX_GPUFamily1_v2, Version(1, 2),
        //Availability
        {
            true,
            false,
            false,
            false,
            false,
            false,
            true,
            false,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            false,
            false,
            true,
            true,
            true,
            false,
            true,
            true,
            false,
            true,
            true,
            true,
            false,
            true,
            true,
            false,
            false,
            false,
            true,
            true,
        },
        //Limits
        {
            31,
            31,
            128,
            16,
            31,
            4000,
            1024,
            32000,
            16,
            64000,
            32,
            128,
            65536,
            64,
            1000000000,
            256,
            16384,
            16384,
            16384,
            2048,
            2048,
            256,
            0,
            8,
            511,
            (size_t)-1,
            65528,
        },
        //Capabilities
        {
            MetalFeatureSetCapability::FILTER,
            MetalFeatureSetCapability::ALL,
            MetalFeatureSetCapability::NONE,
            MetalFeatureSetCapability::ALL,
            MetalFeatureSetCapability::WRITE | MetalFeatureSetCapability::COLOR | MetalFeatureSetCapability::MSAA,
            MetalFeatureSetCapability::ALL,
            MetalFeatureSetCapability::WRITE | MetalFeatureSetCapability::COLOR | MetalFeatureSetCapability::MSAA,
            MetalFeatureSetCapability::ALL,
            MetalFeatureSetCapability::ALL,
            MetalFeatureSetCapability::NONE,
            MetalFeatureSetCapability::ALL,
            MetalFeatureSetCapability::WRITE | MetalFeatureSetCapability::COLOR | MetalFeatureSetCapability::MSAA,
            MetalFeatureSetCapability::NONE,
            MetalFeatureSetCapability::WRITE | MetalFeatureSetCapability::COLOR | MetalFeatureSetCapability::MSAA,
            MetalFeatureSetCapability::ALL,
            MetalFeatureSetCapability::ALL,
            MetalFeatureSetCapability::WRITE | MetalFeatureSetCapability::COLOR | MetalFeatureSetCapability::MSAA,
            MetalFeatureSetCapability::ALL,
            MetalFeatureSetCapability::ALL,
            MetalFeatureSetCapability::FILTER | MetalFeatureSetCapability::COLOR | MetalFeatureSetCapability::MSAA | MetalFeatureSetCapability::RESOLVE | MetalFeatureSetCapability::BLEND,
            MetalFeatureSetCapability::ALL,
            MetalFeatureSetCapability::WRITE | MetalFeatureSetCapability::COLOR | MetalFeatureSetCapability::MSAA,
            MetalFeatureSetCapability::ALL,
            MetalFeatureSetCapability::FILTER | MetalFeatureSetCapability::COLOR | MetalFeatureSetCapability::MSAA | MetalFeatureSetCapability::RESOLVE | MetalFeatureSetCapability::BLEND,
            MetalFeatureSetCapability::ALL,
            MetalFeatureSetCapability::WRITE | MetalFeatureSetCapability::COLOR | MetalFeatureSetCapability::MSAA,
            MetalFeatureSetCapability::ALL,
            MetalFeatureSetCapability::FILTER,
            MetalFeatureSetCapability::WRITE | MetalFeatureSetCapability::COLOR | MetalFeatureSetCapability::MSAA,
            MetalFeatureSetCapability::ALL,
            MetalFeatureSetCapability::ALL,
            MetalFeatureSetCapability::WRITE | MetalFeatureSetCapability::COLOR | MetalFeatureSetCapability::MSAA,
            MetalFeatureSetCapability::ALL,
            MetalFeatureSetCapability::WRITE | MetalFeatureSetCapability::COLOR | MetalFeatureSetCapability::MSAA,
            MetalFeatureSetCapability::ALL,
            MetalFeatureSetCapability::NONE,
            MetalFeatureSetCapability::NONE,
            MetalFeatureSetCapability::NONE,
            MetalFeatureSetCapability::FILTER,
            MetalFeatureSetCapability::FILTER,
            MetalFeatureSetCapability::FILTER | MetalFeatureSetCapability::MSAA | MetalFeatureSetCapability::RESOLVE,
            MetalFeatureSetCapability::FILTER | MetalFeatureSetCapability::MSAA | MetalFeatureSetCapability::RESOLVE,
            MetalFeatureSetCapability::MSAA,
            MetalFeatureSetCapability::FILTER | MetalFeatureSetCapability::MSAA | MetalFeatureSetCapability::RESOLVE,
            MetalFeatureSetCapability::FILTER | MetalFeatureSetCapability::MSAA | MetalFeatureSetCapability::RESOLVE,
            MetalFeatureSetCapability::MSAA,
            MetalFeatureSetCapability::MSAA,
            MetalFeatureSetCapability::NONE,
        },
    },
#endif
};
static bool GetStandardFeatureSet(MetalFeatureSet& result, MTLFeatureSet gpuFamily)
{
    for (size_t i = 0; i < FINJIN_COUNT_OF(standardFeatureSets); i++)
    {
        if (standardFeatureSets[i].gpuFamily == gpuFamily)
        {
            result = standardFeatureSets[i];
            return true;
        }
    }
    return false;
}
